# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5efb9328b2c00dbcfd8bf99895f2bc8b1fc3e5a17e6a383e3a4fa3736609972a368c2db43b477a309a2073406c328af4daa2911e73cf47e26d092fc6acba2fc3

test:
  secret_key_base: 0bd7ab9d678f9cd0b12116e071508e5b01a686669044f6ca7a032806e770d275a63ff977164a8078996e712bf24a93e45b9faa28e3d33b6bdc94df7558e131ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
